### ISSUE TITLE
Plugin not show other client's props

### ISSUE THREAD

**Issue by WilPounder** [IdylRS/prop-hunt#6]
Hello Idyl, hope all I well.

My clanmates and I are having issues getting the plugin to work.  Our avatars are not showing as props on other users' screens.  I have confirmed the following plugins are not active on both clients.  Both Prop Hunt Plugins are on, with name and comma correct.
Entity Hider
Player Indicator

I can post screenshots of our setup and what our current view is.  What would be the best way to send this over?

**Comment by IdylRS** [comment]
This was a server issue, looks like it's resolved now! let me know if it's still bugging.

**Comment by WilPounder** [comment]
Clan Phoenix thanks you!  Confirmed on our end!

**Comment by mithom** [comment]
for me and my friends it is still not working. are there known issues or is it most likely a plugin conflict? i don't have many plugins installed. thanks for making the plugin available btw

**Comment by mithom** [comment]
2023-05-10 01:03:35 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at com.idyl.prophunt.PropHuntDataManager.urlifyString(PropHuntDataManager.java:122)
	at com.idyl.prophunt.PropHuntDataManager.updatePropHuntApi(PropHuntDataManager.java:29)
	at com.idyl.prophunt.PropHuntPlugin.onConfigChanged(PropHuntPlugin.java:189)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.config.ConfigManager.setConfiguration(ConfigManager.java:824)
	at net.runelite.client.config.ConfigManager.setConfiguration(ConfigManager.java:831)
	at net.runelite.client.config.ConfigManager.setConfiguration(ConfigManager.java:846)
	at net.runelite.client.config.ConfigManager.setRSProfileConfiguration(ConfigManager.java:889)
	at net.runelite.client.plugins.slayer.SlayerPlugin.setProfileConfig(SlayerPlugin.java:291)
	at net.runelite.client.plugins.slayer.SlayerPlugin.onVarbitChanged(SlayerPlugin.java:337)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:191)
	at client.qz(client.java:21006)
	at client.ia(client.java:6706)
	at client.hq(client.java:2846)
	at client.bd(client.java:1133)
	at bm.ap(bm.java:353)
	at bm.run(bm.java:332)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Nailz-Z** [comment]
Idyl the mod isnt working for me and a friend. Both have names typed in. All that. Trying to get this working for a video
